{ @Reference
	@Tag {avsfag2020}
	@Type {Misc}
	@Title {"/"AIDG"/" Writing Guide v 1.0}
	@Author {Avsfag}
	@Year {2020}
	@URL {https://guide.aidg.club/AIDG-Writing-Guide/AIDG%20Writing%20Guide.html}
#	entrysubtype {coomer}
#	annotation {/aidg/'s premiere guide for new learners and general concepts.}
}

{ @Reference
	@Tag {branwen2020}
	@Title {GPT-3 Creative Fiction}
	@Type {Misc}
	@Author {Gwern Branwen}
	@Year {2020}
	@URL {https://www.gwern.net/GPT-3}
	@Annote {coomer}
	@Note {An absolutely massive technical compendium of Gwern's experiments with GPT-3 and its creative writing abilities.}
	@Abstract {Creative writing by OpenAI's GPT-3 model, demonstrating poetry, dialogue, puns, literary parodies, and storytelling. Plus advice on effective GPT-3 prompt programming "&" avoiding common errors.}
}

{ @Reference
	@Tag {failedsave2020}
	@Title {Guide to Erotic Storytelling with AI Dungeon}
	@Type {Misc}
	@Author {FailedSave}
	@Year {2020}
	@URL {https://github.com/FailedSave/storytelling-guide/blob/master/Guide.md}
	@Annote {coomer}
	@Note {A predecessor to ``A Coomer's Guide to AI Dungeon''. Quite old now, missing a lot, but it's written in a way that steps you through the process of cultivating a piece of erotic writing as it evolves, which is still a valuable perspective.}
	@Abstract {With some effort and experimentation I've had really good luck writing erotic stories for myself with the help of AI Dungeon. I find that doing porn myself—with the AI helping—works really well for a couple reasons. First, I like to read porn in the second person, and AI Dungeon makes that really easy. Second, it's really hot to read something that's a surprise. Often the AI's output makes no sense, but it's good often enough that with some work you can write plenty of hot stories.}
}

{ @Reference
	@Tag {penn2011}
	@Title {The Punctuation Guide}
	@Type {Misc}
	@Author {Jordan Penn}
	@Year {2011}
	@URL {https://www.thepunctuationguide.com/}
	@Annote {coomer}
	@Note {An excellent resource for learning how to effectively use every kind of punctuation.}
	@Abstract {In the early years of written English, punctuation served to mark pauses and other aspects of speech when text was read aloud. Over the subsequent centuries, punctuation marks were refined, eventually being used to indicate grammatical relationships between parts of a sentence. Today, punctuation serves both purposes, though the grammatical function dominates.}
}

{ @Reference
	@Tag {wallenberg2004}
	@Title {Punctuating Dialogue}
	@Type {Misc}
	@Author {Wallenberg}
	@Year {2004}
	@Month {May}
	@URL {http://www.tinareber.com/wp-content/uploads/2013/08/punctuating.pdf}
	@Annote {coomer}
	@Note {Incredibly handy PDF file for keeping the many rules of dialogue formatting straight, so your story's dialogue is high-quality and consistent.}
}

